# Generated by Django 4.1.5 on 2023-01-11 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Nombre Completo"),
                ),
                (
                    "country_origin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="País Origen",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "Actor",
                "verbose_name_plural": "Actores",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Nombre Completo"),
                ),
                (
                    "years_experience",
                    models.SmallIntegerField(
                        default=1, verbose_name="Años de experiencia"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "Director",
                "verbose_name_plural": "Directores",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "Genero",
                "verbose_name_plural": "Generos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "overview",
                    models.TextField(blank=True, null=True, verbose_name="Resumen"),
                ),
                (
                    "released_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Año lanzamiento"
                    ),
                ),
                (
                    "certificate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("u", "U"),
                            ("a", "A"),
                            ("ua", "UA"),
                            ("r", "R"),
                            ("pg-13", "PG-13"),
                            ("other", "Other"),
                        ],
                        max_length=6,
                        null=True,
                        verbose_name="Certificado",
                    ),
                ),
                (
                    "runtime",
                    models.IntegerField(
                        help_text="Duración de la película en minutos",
                        verbose_name="Duración",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=1.0, null=True, verbose_name="Raiting IMDB"
                    ),
                ),
                (
                    "gross",
                    models.PositiveIntegerField(default=0, verbose_name="Recaudo"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
                (
                    "actores",
                    models.ManyToManyField(
                        related_name="get_actores", to="movies.actor"
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="movies.director",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        related_name="get_genres",
                        to="movies.genre",
                        verbose_name="Genero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Película",
                "verbose_name_plural": "Películas",
                "ordering": ["-rating"],
            },
        ),
    ]
